version: "2"

services:
  runtime:
    image: public.ecr.aws/nupano/nupano-runtime:3.1.1
    environment:
      - SERVER_PORT=61100
      - NUPANO_APPS_DOCKER_HOST=unix:///var/run/balena.sock
      - LOGGING_LEVEL_COM_NUPANO=INFO
      - NUPANO_DOMAIN=nupano.com
      - NUPANO_UPDATE_ENABLED=false
      #- NUPANO_DESCRIPTION_MANUFACTURER=WELOTEC
      #- NUPANO_DESCRIPTION_MODEL_NAME=Arrakis-pico-MK3
      #- NUPANO_DESCRIPTION_SERIAL_NUMBER=2206002455
    volumes:
      - nupano_data:/nupano
    networks:
      - nupano_network
    ports:
      - 61100:61100/tcp
    labels:
      io.balena.features.balena-socket: '1'
networks:
  nupano_network:
    driver: bridge
volumes:
  nupano_data:
